{% set name = "arxiv" %}
{% set version = "2.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arxiv-{{ version }}.tar.gz
  sha256: 32365221994d2cf05657c1fadf63a26efc8ccdec18590281ee03515bfef8bc4e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - feedparser >=6.0.10,<6.1.dev0
    - requests >=2.32.0,<2.33.dev0

test:
  # Something is wrong with the way the test suite is accessing the internet, disable for now
  # source_files:
  #   - tests
  imports:
    - arxiv
  commands:
    - pip check
    # - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    # - pytest >=6.2.2

about:
  home: https://github.com/lukasschwab/arxiv.py
  summary: 'Python wrapper for the arXiv API: http://arxiv.org/help/api/'
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: http://lukasschwab.me/arxiv.py/index.html

extra:
  recipe-maintainers:
    - thewchan
