{% set name = "arxiv" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arxiv-{{ version }}.tar.gz
  sha256: bd3950d78c01a4bbf56a0c2e02f25389940628f557825628b4d1f91d349f1bc9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - feedparser
    - python >=3.6

test:
  imports:
    - arxiv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lukasschwab/arxiv.py
  summary: 'Python wrapper for the arXiv API: http://arxiv.org/help/api/'
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: http://lukasschwab.me/arxiv.py/index.html

extra:
  recipe-maintainers:
    - thewchan
