{% set name = "arxiv" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arxiv-{{ version }}.tar.gz
  sha256: 9010cf132bcfb67c07bd363c49d519365310f92ac9da1a06509f712798265987

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - feedparser
    - python >=3.6
    - requests

test:
  imports:
    - arxiv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lukasschwab/arxiv.py
  summary: 'Python wrapper for the arXiv API: http://arxiv.org/help/api/'
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: http://lukasschwab.me/arxiv.py/index.html

extra:
  recipe-maintainers:
    - thewchan
