{% set name = "arxiv" %}
{% set version = "1.4.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arxiv-{{ version }}.tar.gz
  sha256: 100c8d6b9cd04c7f55f11b34616beb7a1623ab0564b66161b4aeeeb8912c5806

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - feedparser
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - arxiv
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/lukasschwab/arxiv.py
  summary: 'Python wrapper for the arXiv API: http://arxiv.org/help/api/'
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: http://lukasschwab.me/arxiv.py/index.html

extra:
  recipe-maintainers:
    - thewchan
