{% set name = "arxiv" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arxiv-{{ version }}.tar.gz
  sha256: 97f910dadf97169793ab3fcf12e75d23cb9dac4dc7c16de8b09492cde179da9f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - feedparser
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - arxiv
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/lukasschwab/arxiv.py
  summary: 'Python wrapper for the arXiv API: http://arxiv.org/help/api/'
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: http://lukasschwab.me/arxiv.py/index.html

extra:
  recipe-maintainers:
    - thewchan
